In [104]:
#Import dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

In [105]:
#Convert CSV into Dataframe
file1 = "Downloads/Winter-202201-citibike-tripdata.csv"
file2 = "Downloads/Fall-202210-citibike-tripdata.csv"
file3 = "Downloads/Summer-202207-citbike-tripdata.csv"
file4 = "Downloads/Spring-202204-citibike-tripdata.csv"

#Read CSV and rename by season
Winter_data = pd.read_csv(file1, encoding="UTF-8")
Fall_data = pd.read_csv(file2, encoding="UTF-8")
Summer_data = pd.read_csv(file3, encoding="UTF-8")
Spring_data = pd.read_csv(file4, encoding="UTF-8")

In [106]:
#Merge each tables
df = [Winter_data, Fall_data, Summer_data, Spring_data]

In [107]:
#Create new Dataframe
file5 = "Downloads/Season-Citibike-tripdata.csv"
trip_history = pd.read_csv(file5, encoding="UTF-8")
trip_history

,ride_id,rideable_type,started_at,ended_at,Trip Duration,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CA5837152804D4B5,electric_bike,1/26/2022 18:50,1/26/2022 18:51,0:01:00,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,1/28/2022 13:14,1/28/2022 13:20,0:06:00,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,1/10/2022 19:55,1/10/2022 20:00,0:05:00,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,1/26/2022 7:54,1/26/2022 7:55,0:00:00,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,1/13/2022 18:44,1/13/2022 18:45,0:00:00,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287346,13C1C453508F048A,classic_bike,4/24/2022 12:52,4/24/2022 13:06,0:14:00,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,9 St HBLR - Jackson St & 8 St,HB305,40.736982,-74.027781,40.747907,-74.038412,member
287347,B7E454B8886D7826,electric_bike,4/30/2022 11:45,4/30/2022 11:54,0:08:00,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,12 St & Sinatra Dr N,HB201,40.736982,-74.027781,40.750604,-74.024020,member
287348,20D6A9E7C8291984,classic_bike,4/28/2022 14:28,4/28/2022 14:41,0:13:00,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Bloomfield St & 15 St,HB203,40.736982,-74.027781,40.754530,-74.026580,member
287349,2AEB863A4F683CAE,electric_bike,4/9/2022 17:37,4/9/2022 17:46,0:09:00,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Bloomfield St & 15 St,HB203,40.736982,-74.027781,40.754530,-74.026580,casual
287350,AB2C885E7051B2D4,classic_bike,4/2/2022 15:54,4/2/2022 16:02,0:08:00,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Clinton St & 7 St,HB303,40.736982,-74.027781,40.745420,-74.033320,casual

In [108]:
#Total count of trips
trip_history.count()

ride_id               287350
rideable_type         287350
started_at            287350
ended_at              287350
Trip Duration         287351
start_station_name    287350
start_station_id      287350
end_station_name      286075
end_station_id        286075
start_lat             287350
start_lng             287350
end_lat               286584
end_lng               286584
member_casual         287350
dtype: int64

In [109]:
#Clean up dataframe to remove any excess information not necessary to analyze trends noticed in the data collected
citibike = trip_history.drop(columns=['ride_id', 'started_at', 'ended_at', 'start_station_name', 'end_station_name'])
citibike

,rideable_type,Trip Duration,start_station_id,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,electric_bike,0:01:00,HB201,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,classic_bike,0:06:00,JC038,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,classic_bike,0:05:00,JC038,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,electric_bike,0:00:00,HB201,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,electric_bike,0:00:00,HB201,HB201,40.750604,-74.024020,40.750604,-74.024020,member
...,...,...,...,...,...,...,...,...,...
287346,classic_bike,0:14:00,HB103,HB305,40.736982,-74.027781,40.747907,-74.038412,member
287347,electric_bike,0:08:00,HB103,HB201,40.736982,-74.027781,40.750604,-74.024020,member
287348,classic_bike,0:13:00,HB103,HB203,40.736982,-74.027781,40.754530,-74.026580,member
287349,electric_bike,0:09:00,HB103,HB203,40.736982,-74.027781,40.754530,-74.026580,casual
287350,classic_bike,0:08:00,HB103,HB303,40.736982,-74.027781,40.745420,-74.033320,casual

In [110]:
citibike.to_csv("Downloads/Season_CitiBike_Data.csv", index=False)